Feature/club CRUD 간단하게 구현
CalmCrews/silver_backend pull request #43
Opened 2023-08-03 04:09 UTC by imjanghyeok

## 작업 내용

- ClubListCreateAPIView 구현 (자기가 참가하고 있는 모임만 필터링)
- ClubRetrieveUpdateAPIView 구현 (사용자 권한 인증 기능 x, 리팩토링 필요)

## 기타 사항

- create할 시 tag 추가하는 기능 필요
- 사용자권한 인증 기능 필요

## 참고 사항

![image](https://github.com/CalmCrews/silver_backend/assets/66295199/29dde538-eb53-4b6f-8f92-c97d33a3f694)
![image](https://github.com/CalmCrews/silver_backend/assets/66295199/79e404ec-6e86-4d9e-ae8d-1cff4f1b5e93)

2023-08-03 04:57 UTC, LeLu815 approved these changes

2023-08-03 05:15 UTC, koomchang commented on webapp/club/views/clubRetrieveAPIView.py
> +    serializer_class = ClubRetrieveSerializer
모임(club) 조회 수정 기능인데 queryset 을 clubtag 로 가져 오는 것은 맞지 않는 것 같습니다.


ClubTag view를 만들어서 클럽 태그에 대한 조작을 해주는 것이 좋아 보입니다.

2023-08-03 05:30 UTC, koomchang commented on webapp/club/views/clubListAPIView.py
> +            'nickname': self.request.data.get('nickname')
http://localhost:8888/clubs/

에서 nickname 없이 post 요청을 보냈을 때 userclub serializer 로 연결이 되고 있는데

<img width="1146" alt="image" src="https://github.com/CalmCrews/silver_backend/assets/90228925/a7333d0d-db93-4974-88be-f8368b5e5f67">

userclub을 user,club만 저장하고 nickname은 null인 객체로 우선 만들고 nickname을 따로 업데이트 할 수 있는 view를 따로 만드는게 좋아 보입니다!

2023-08-03 05:31 UTC, koomchang requested changes
고생하셨습니다 comment 확인 부탁드립니다 :)

2023-08-03 05:32 UTC, koomchang commented on webapp/club/views/clubRetrieveAPIView.py
> +class ClubRetrieveAPIView(RetrieveUpdateAPIView):
class retrieve, update를 상속받으면 class 이름도 맞게 바꿔주시는게 좋아보입니다!

2023-08-03 05:34 UTC, koomchang commented on webapp/club/views/clubRetrieveAPIView.py
> +from club.serializers import ClubRetrieveSerializer
import 정리도 해주세요 ^_^

2023-08-04 04:48 UTC, koomchang commented on webapp/club/serializers/userClubNicknameSerializer.py
> +            'user',
user 정보가 현재 유저 아이디가 나오는데 UserSerializer를 통해 같이 보여주는 식으로 하면 좋을 것 같아요!

`from user.serializesrs import UserSerializer`

2023-08-04 04:49 UTC, koomchang requested changes
Club 모델에서 str 함수를 이용하여 오브젝트 반환이 아닌 클럽 이름 반환 등을 해주면 admin 페이지에서도 더 보기 좋을 것 같습니다~

2023-08-04 09:03 UTC, koomchang approved these changes

2023-08-04 09:03 UTC, merged